# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ QA_Release1 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      sfdx: "node_modules/sfdx-cli/bin/run"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE and sets up node(npm), so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '>=14'
        check-latest: true

    # Runs a single command using the runners shell
    - name: 'Build and Deploy'
      run: |
        npm install sfdx-cli
        $sfdx --version
        $sfdx plugins:install @salesforce/sfdx-scanner
 # Runs a set of commands using the runners shell
    - name: 'Decrypt file'
      run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
    - name: 'Authorize'
      run: |
        echo username value ${{ secrets.USERNAME_STAGING }}
        $sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY_STG }} --username=${{ secrets.USERNAME_STG }} --jwtkeyfile server.key --setdefaultdevhubusername --setalias=hub-org
    - name: "Install App and Create Delta"   
      run: |
        sudo npm install sfdx-git-delta@latest -g
        git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
        git fetch --all
        git --no-pager diff --name-status QA_Release1 origin/staging_Release1
        sgd --to QA_Release1 --from origin/staging_Release1 --repo . --output .
        cat package/package.xml
    - name: 'Convert Metadata'
      run: $sfdx force:source:convert --rootdir=force-app --manifest=package/package.xml --outputdir=convert
    - name: 'Run Test on Metadata'
      run: $sfdx force:mdapi:deploy --deploydir=convert -u hub-org
